apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-python
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
    - host: python.time.app
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: app-python
                port:
                  number: 5000